# Generated by Django 5.0.2 on 2024-03-08 09:16

import django.db.models.deletion
import django.utils.timezone
import doctor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        ('users', '0003_alter_doctor_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('times', doctor.models.MultiSelectField(choices=[('08:00:00', 'Morning'), ('13:00:00', 'After Noon'), ('20:00:00', 'Night')], max_length=10000)),
                ('condition', models.CharField(max_length=20)),
                ('dosage', models.CharField(default=1, max_length=100)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('number_of_days', models.PositiveIntegerField()),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.prescription')),
            ],
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicines',
            field=models.ManyToManyField(related_name='pre_medicines', to='doctor.prescriptionmedicine'),
        ),
    ]
