# Generated by Django 5.0.2 on 2024-03-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescriptionmedicine',
            old_name='number_of_days',
            new_name='duration',
        ),
        migrations.AddField(
            model_name='prescription',
            name='advice',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='times',
            field=models.JSONField(default=list),
        ),
    ]
